version: '3.3'

services:
  postgres:
    container_name: trms-postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: trms
      POSTGRES_USER: trms
      POSTGRES_PASSWORD: trms_password
    ports:
      - "5433:5432"
    volumes:
      - trms_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trms -d trms"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    container_name: trms-ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - trms_ollama:/root/.ollama
    restart: unless-stopped

volumes:
  trms_postgres_data:
  trms_ollama: